-- Módulo de Inventario (pedido 2026-08-27).
--
-- Modelo: el stock vigente vive en productos.stock (lectura barata desde
-- cualquier pantalla) y cada cambio queda registrado en inventario_movimientos
-- como libro de movimientos (entrada / salida / ajuste), con el stock
-- resultante estampado en cada fila para poder auditar sin recalcular.
-- El backend es el único que escribe: actualiza productos.stock y anota el
-- movimiento en la misma operación.

alter table productos
  add column if not exists stock numeric not null default 0;

alter table productos
  add column if not exists stock_minimo numeric not null default 0;

comment on column productos.stock is
  'Stock vigente en unidades. Lo mantiene el backend del módulo Inventario: no editar a mano (cada cambio debe quedar en inventario_movimientos).';
comment on column productos.stock_minimo is
  'Umbral de alerta del módulo Inventario. 0 = sin umbral definido.';

create table if not exists inventario_movimientos (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references productos (id) on delete cascade,
  -- El SKU se copia al momento del movimiento: si el producto cambia de SKU
  -- después, el historial sigue diciendo con cuál se movió.
  sku text,
  -- entrada / salida: cantidad positiva y el signo lo pone el tipo.
  -- ajuste: la cantidad es el DELTA aplicado (puede ser negativa) tras un
  -- conteo físico; motivo típico "Inventario físico" o "Carga inicial".
  tipo text not null check (tipo in ('entrada', 'salida', 'ajuste')),
  cantidad numeric not null,
  stock_resultante numeric not null,
  motivo text,
  -- Referencia libre: N° de OC del proveedor, código de cotización, guía, etc.
  referencia text,
  -- Costo unitario de la entrada (para valorizar compras); null en el resto.
  costo_unitario numeric,
  usuario_email text,
  created_at timestamptz not null default now()
);

create index if not exists inventario_movimientos_producto_idx
  on inventario_movimientos (producto_id, created_at desc);

comment on table inventario_movimientos is
  'Libro de movimientos del módulo Inventario. Una fila por entrada, salida o ajuste; stock_resultante = stock del producto después del movimiento.';
