-- Submódulo de Proveedores: catálogo de proveedores para órdenes de compra y
-- gestión general. Solo lo administra el rol admin (gate en el frontend).
create table if not exists public.proveedores (
  id           bigint generated by default as identity primary key,
  razon_social text not null,
  rut          text,
  correo       text,
  telefono     text,
  contacto     text,
  direccion    text,
  rubro        text,
  observaciones text,
  creado_por   text,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

create index if not exists idx_proveedores_razon on public.proveedores (lower(razon_social));
