-- Explorador de precios dentales del portal de clientes (2026-09-04).
-- Cada búsqueda guarda una captura por producto encontrado en las tiendas
-- externas (estilo Knasta/SoloTodo): con eso se construye el histórico
-- (precio mínimo/máximo registrado y variación contra la captura anterior).
create table if not exists explorador_precios (
  id bigint generated by default as identity primary key,
  consulta text not null,
  tienda text not null,
  nombre text not null,
  url text not null,
  precio integer not null,
  precio_normal integer,          -- precio sin oferta, si la tienda lo informa
  capturado_at timestamptz not null default now()
);

-- El histórico se consulta por producto (url) y las capturas por búsqueda.
create index if not exists explorador_precios_url_idx
  on explorador_precios (url, capturado_at desc);
create index if not exists explorador_precios_consulta_idx
  on explorador_precios (consulta, capturado_at desc);

alter table explorador_precios enable row level security;
-- Solo el backend (service role) escribe y lee; sin políticas para anon.
